/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class winkeyboard_Keyboard */

#ifndef _Included_winkeyboard_Keyboard
#define _Included_winkeyboard_Keyboard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     winkeyboard_Keyboard
 * Method:    KeyPress
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_winkeyboard_Keyboard_KeyPress
  (JNIEnv *, jobject, jint);

/*
 * Class:     winkeyboard_Keyboard
 * Method:    KeyRelease
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_winkeyboard_Keyboard_KeyRelease
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
